### ISSUE TITLE
Table 'dbpo.examples' doesn't exist 

### ISSUE THREAD

**Issue by alailsonribeiro** [davidyell/CakePHP-NiceAdminBakeScripts#13]
Where is sql our how to I create a table **db.examples** ?

**bin/cake bake template --theme=NiceAdminBakeTheme Examples**
`Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table **'db.examples' doesn't exist** in [/www/app/vendor/cakephp/cakephp/src/Database/Schema/Collection.php, line 131]`

**bin/cake bake template --theme=NiceAdminBakeTheme --prefix=Admin Examples**
`Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table **'db.examples' doesn't exist** in [/www/app/vendor/cakephp/cakephp/src/Database/Schema/Collection.php, line 131]`

**Comment by davidyell** [comment]
You will need to create the database table. The `Examples` given in the readme is there for you to replace with the name of the Table you are baking the theme for.

`bin/cake bake template --theme=NiceAdminBakeTheme Posts`
`bin/cake bake template --theme=NiceAdminBakeTheme Users`
etc
