### ISSUE TITLE
Missing ]

### ISSUE THREAD

**Issue by ribafs** [davidyell/CakePHP-NiceAdminBakeScripts#15]
Thank you for your plugin. Very good.

Missing ] continue

See:
bin/cake bake controller --theme=NiceAdminBakeTheme Customers

Baking controller class for Customers...

Creating file /backup/www/cake/cake3theme/src/Controller/CustomersController.php
Wrote `/backup/www/cake/cake3theme/src/Controller/CustomersController.php`
Exception: syntax error, unexpected ')', expecting ']' in [/backup/www/cake/cake3theme/src/Controller/CustomersController.php, line 25]
2019-06-07 16:32:04 Error: [ParseError] syntax error, unexpected ')', expecting ']' in /backup/www/cake/cake3theme/src/Controller/CustomersController.php on line 25

**Comment by davidyell** [comment]
Related to #14 

Thanks, I'll take a look at this.

**Comment by davidyell** [comment]
I cannot replicate this issue.
